// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	"github.com/go-kit/kit/transport/grpc"
	"github.com/lattecake/kpaas-alert/pkg/endpoint"
	"github.com/lattecake/kpaas-alert/pkg/grpc/pb"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	alert    grpc.Handler
	getAlert grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.KpaasAlertServer {
	return &grpcServer{
		alert:    makeAlertHandler(endpoints, options["Alert"]),
		getAlert: makeGetAlertHandler(endpoints, options["GetAlert"]),
	}
}
