// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kpaas_alert/pkg/grpc/pb/kpaas_alert.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	kpaas_alert/pkg/grpc/pb/kpaas_alert.proto

It has these top-level messages:
	AlertRequest
	AlertReply
	GetAlertRequest
	GetAlertReply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AlertRequest struct {
}

func (m *AlertRequest) Reset()                    { *m = AlertRequest{} }
func (m *AlertRequest) String() string            { return proto.CompactTextString(m) }
func (*AlertRequest) ProtoMessage()               {}
func (*AlertRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AlertReply struct {
}

func (m *AlertReply) Reset()                    { *m = AlertReply{} }
func (m *AlertReply) String() string            { return proto.CompactTextString(m) }
func (*AlertReply) ProtoMessage()               {}
func (*AlertReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetAlertRequest struct {
}

func (m *GetAlertRequest) Reset()                    { *m = GetAlertRequest{} }
func (m *GetAlertRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAlertRequest) ProtoMessage()               {}
func (*GetAlertRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetAlertReply struct {
}

func (m *GetAlertReply) Reset()                    { *m = GetAlertReply{} }
func (m *GetAlertReply) String() string            { return proto.CompactTextString(m) }
func (*GetAlertReply) ProtoMessage()               {}
func (*GetAlertReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*AlertRequest)(nil), "pb.AlertRequest")
	proto.RegisterType((*AlertReply)(nil), "pb.AlertReply")
	proto.RegisterType((*GetAlertRequest)(nil), "pb.GetAlertRequest")
	proto.RegisterType((*GetAlertReply)(nil), "pb.GetAlertReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for KpaasAlert service

type KpaasAlertClient interface {
	Alert(ctx context.Context, in *AlertRequest, opts ...grpc.CallOption) (*AlertReply, error)
	GetAlert(ctx context.Context, in *GetAlertRequest, opts ...grpc.CallOption) (*GetAlertReply, error)
}

type kpaasAlertClient struct {
	cc *grpc.ClientConn
}

func NewKpaasAlertClient(cc *grpc.ClientConn) KpaasAlertClient {
	return &kpaasAlertClient{cc}
}

func (c *kpaasAlertClient) Alert(ctx context.Context, in *AlertRequest, opts ...grpc.CallOption) (*AlertReply, error) {
	out := new(AlertReply)
	err := grpc.Invoke(ctx, "/pb.KpaasAlert/Alert", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kpaasAlertClient) GetAlert(ctx context.Context, in *GetAlertRequest, opts ...grpc.CallOption) (*GetAlertReply, error) {
	out := new(GetAlertReply)
	err := grpc.Invoke(ctx, "/pb.KpaasAlert/GetAlert", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for KpaasAlert service

type KpaasAlertServer interface {
	Alert(context.Context, *AlertRequest) (*AlertReply, error)
	GetAlert(context.Context, *GetAlertRequest) (*GetAlertReply, error)
}

func RegisterKpaasAlertServer(s *grpc.Server, srv KpaasAlertServer) {
	s.RegisterService(&_KpaasAlert_serviceDesc, srv)
}

func _KpaasAlert_Alert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KpaasAlertServer).Alert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KpaasAlert/Alert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KpaasAlertServer).Alert(ctx, req.(*AlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KpaasAlert_GetAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KpaasAlertServer).GetAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KpaasAlert/GetAlert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KpaasAlertServer).GetAlert(ctx, req.(*GetAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KpaasAlert_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.KpaasAlert",
	HandlerType: (*KpaasAlertServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Alert",
			Handler:    _KpaasAlert_Alert_Handler,
		},
		{
			MethodName: "GetAlert",
			Handler:    _KpaasAlert_GetAlert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kpaas_alert/pkg/grpc/pb/kpaas_alert.proto",
}

func init() { proto.RegisterFile("kpaas_alert/pkg/grpc/pb/kpaas_alert.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0xcc, 0x2e, 0x48, 0x4c,
	0x2c, 0x8e, 0x4f, 0xcc, 0x49, 0x2d, 0x2a, 0xd1, 0x2f, 0xc8, 0x4e, 0xd7, 0x4f, 0x2f, 0x2a, 0x48,
	0xd6, 0x2f, 0x48, 0xd2, 0x47, 0x12, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48,
	0x52, 0xe2, 0xe3, 0xe2, 0x71, 0x04, 0x09, 0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x28, 0xf1,
	0x70, 0x71, 0x41, 0xf9, 0x05, 0x39, 0x95, 0x4a, 0x82, 0x5c, 0xfc, 0xee, 0xa9, 0x25, 0x28, 0x0a,
	0xf8, 0xb9, 0x78, 0x11, 0x42, 0x05, 0x39, 0x95, 0x46, 0xd9, 0x5c, 0x5c, 0xde, 0x20, 0xa3, 0xc1,
	0x42, 0x42, 0x9a, 0x5c, 0xac, 0x10, 0x86, 0x80, 0x5e, 0x41, 0x92, 0x1e, 0xb2, 0x4e, 0x29, 0x3e,
	0x24, 0x91, 0x82, 0x9c, 0x4a, 0x21, 0x23, 0x2e, 0x0e, 0x98, 0x49, 0x42, 0xc2, 0x20, 0x39, 0x34,
	0xab, 0xa4, 0x04, 0x51, 0x05, 0x0b, 0x72, 0x2a, 0x93, 0xd8, 0xc0, 0x2e, 0x37, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xc5, 0x85, 0xeb, 0x4b, 0xe6, 0x00, 0x00, 0x00,
}
